version: "3"

services:
  postgres:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_USER: lucky
      POSTGRES_PASSWORD: developer
    volumes:
      - db:/var/lib/postgresql
    networks:
      - internal
    ports:
      - 5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SHARDS_CACHE_PATH: /data/.shards
      DB_HOST: postgres
      DB_USERNAME: lucky
      DB_PASSWORD: developer
    volumes:
      - .:/data
    # command: echo "Crystal Version" && crystal -v && \
    #   echo "Node Version" && node -v &&  \
    #   echo "NPM Version" && npm -v &&  \
    #   script/setup && lucky dev # sleep infinity
    # command: script/ci_checks
    # command: lucky dev
    depends_on:
      - postgres
    networks:
      - internal
    ports:
      - 3001:3001
      - 5000:5000
    command: bash -c "script/setup_db && lucky dev"

volumes:
  db:

networks:
  internal: