host: 127.0.0.1
port: 5000
# port: 3001
# # (I think) The above is for Proxying, i.e.:
# web          |    🎉 App running at http://127.0.0.1:3001   
# web          |                                              
# web          | 
# web          | [Browsersync] Proxying: http://127.0.0.1:5000
# web          | [Browsersync] Access URLs:
# web          |  ----------------------------
# web          |  Local: http://localhost:3001
