#!/usr/bin/env bash

shards check || shards install
crystal tool format --check
yarn install --frozen-lockfile --no-progress
yarn prod
crystal build tasks.cr -o ./lucky_tasks

./lucky_tasks db.create
./lucky_tasks db.migrate
./lucky_tasks db.seed.required_data

lucky dev
# crystal spec
